### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by florm2496** [AbelMRobra/linkapp#40]
@AbelMRobra

**Comment by florm2496** [comment]
Que hace la funcion registro_almacenero ? Que es un registro almacenero ?

**Comment by AbelMRobra** [comment]
@florm2496 con respecto a registro_almacenero:

### Que hace la función en términos generales:
Hace un render del template con información, que según como llegue al template mostrara o no algo.

### Que es un registro almacenero :
En este caso, es un registro de la información contable del proyecto, el nombre salio por tradición. Podríamos decir que es como un estado de resultado, el siguiente Link lo explica por si te interesa leerlo:
https://blog.corponet.com.mx/que-es-el-estado-de-resultados-y-cuales-son-sus-objetivos
La diferencia es que es de un proyecto, y tiene en cuenta también lo que se va a realizar. 
Imagina que anotas lo que gastaste, lo que cobraste, lo que venderás y lo que gastaras a futuro; este seria una simplificación del objeto.

### Que hace la función en términos específicos:
Compara los registros de un punto al otro, y calcula la diferencia que hubo tratando de explicarla. Esta función no esta terminada, ya que no he pensado como solucionar los 4 posibles escenarios según las fechas que ingresan, los mismos son:
* Que haya la misma cantidad de proyectos de un punto a otro, así que es solo ver la diferencia de los valores que componen cada uno
* Que se haya agregado mas proyecto (Esto no lo explore)
* Que se haya eliminado algún proyecto (Esto no lo explore)
* Que en alguna de las fechas, el registro no exista

**Comment by florm2496** [comment]
Que significa "extrapolado" en términos de un proyecto

**Comment by florm2496** [comment]
¿Que estas cargando con : {% load humanize %} ?

**Comment by AbelMRobra** [comment]
@florm2496 los proyectos tratamos de tener 3 niveles de estimación de costos:
* Extrapolado
* Aperturado con supuestos grandes
* Aperturado especifico

### Proyecto extrapolado

Es aquella estimación que no se sustenta en ningún tipo de publicación, lo que busca es estimar el costo en función de algún proyecto similar, como resultado se tiene un valor general, sin ningún tipo de apertura que se moverá según su proyecto base. Ejemplo practico: Si el proyecto 1 me costo 100 USD/m2, y tengo un proyecto 2 similar que tiene un tamaño de 10 m2, tomare el valor del proyecto 2 como 1.000 USD totales, y según varié el proyecto 1, variara el proyecto 2.

**Comment by AbelMRobra** [comment]
@florm2496  {% load humanize %} carla el tag "|intcomma" -> son un conjunto de tags para modificar el template que Django proporciona, esta rama particular es para ayudar a la lectura humana de algunas cosas, concretamente "|intcomma" transforma los numeros con separaciones decimales y en centenas. Ejemplo 1000000|intcomma -> 1.000.000

Si usara la propiedad 1000000|floatformat:2|intcomma -> 1.000.000,00

**Comment by florm2496** [comment]
> @florm2496 {% load humanize %} carla el tag "|intcomma" -> son un conjunto de tags para modificar el template que Django proporciona, esta rama particular es para ayudar a la lectura humana de algunas cosas, concretamente "|intcomma" transforma los numeros con separaciones decimales y en centenas. Ejemplo 1000000|intcomma -> 1.000.000
> 
> Si usara la propiedad 1000000|floatformat:2|intcomma -> 1.000.000,00

**Comment by florm2496** [comment]
Que función tiene la app de "cómputos"?

**Comment by AbelMRobra** [comment]
> Que función tiene la app de "cómputos"?

Es una APP que no logramos desarrollar. La idea es poder establecer computos para el calculo de costos. Todo presupuesto es un conjunto de artículos con un precio determinado en una determinada cantidad. Supongamos que los pisos sera la sumatoria de los pisos que hay en cada nivel del edificio, esta app debía reflejar estos computos

**Comment by florm2496** [comment]
Que función tiene la app de "técnica"?

**Comment by AbelMRobra** [comment]
> Que función tiene la app de "técnica"?

Sera la APP que contenga toda la información y funciones del equipo técnico, conjunto de arquitectos e ingenieros que diseñan los proyectos. Entregables que puedes ver:
* Planos
* Memoria de calidades
* Cronogramas
