### ISSUE TITLE
Función de ajuste de precios - Articulos

### ISSUE THREAD

**Issue by AbelMRobra** [AbelMRobra/linkapp#42]
## Integrantes
@joseent 
@AbelMRobra 
@florm2496 

## Explicación
Al momento de cargar una compra, debería el sistema obligar al presupuestador modificar el precio del articulo

## Tareas
Para esto se debe realizar:

- [x] Generar una interfaz que surja luego de cargar una OC @joseent 
- [x] Crear una función que reciba y modifique el dato @florm2496 @AbelMRobra 
- [x] Notificar o hacer un registro @florm2496 @AbelMRobra 
- [x] Testeo @joseent 

## Para el template

Similar al ajuste de cuentas corrientes

**Comment by florm2496** [comment]
Cual es el porcentaje al que debo ajustar el precio del articulo.? a partir del  15% para arriba y para abajo estaría bien?

**Comment by AbelMRobra** [comment]
> Cual es el porcentaje al que debo ajustar el precio del articulo.? a partir del 15% para arriba y para abajo estaría bien?

Mas o menos 5% estaría bien
