### ISSUE TITLE
Reparaciones interfaces JNT

### ISSUE THREAD

**Issue by joseent** [AbelMRobra/linkapp#52]
--compras--
coomparativas - dropdown de accesos y permisos
descargacomp - actualzacion de visual y responsive
principal compras - permisos a nivel 7

--finanzas--
arqueos - agregada columna de inversiones --- falta logica ---
ctacteboleto- arreglada formato de fecha
ctacte - dropdow de accesos y de acciones 
ctacteproyecto - dropdow de accesos y de acciones 
eliminarcuenta - arreglado responsive
eliminarcuota- arreglado responsive
eliminarpagos- arreglado responsive
movimientoadmin - dropdown de accesos y acciones
pagos - dropdown de accesos y acciones

--presupuestos--
crearanalisis - arreglado responsive y modificado formato de cabecera
modificaranalisis - arreglado responsive y modificado formato de cabecera
panelanalisis - dropdown de accesos y acciones
insum_create - arrglado formulario
insum_panel- dropdown de accesos y acciones

--user--
guia - modificacion de tarjetas de monedas y textos en imagenes en caso de error
inicio2 - limpieza y orden general, logo blanco en responsive, styles en su css
sugerencias - modificacion de cabecera, estilo general y acciones -- falta back de mensaje de respuesta ---
inicio.css - css completo y actualizado de inicio para evitar sobrecargarlo

**Comment by AbelMRobra** [comment]
Todo cargado a la fecha

**Comment by AbelMRobra** [comment]
Podes dejar el Issue con una estructura?
