### ISSUE TITLE
Arqueo de caja

### ISSUE THREAD

**Issue by florm2496** [AbelMRobra/linkapp#56]
Requisito: calcular correctamente el total de inversiones en pesos y en USD. Sumar al total de caja consolidada en pesos , estos totales de inversiones en pesos y en dólares . Resolución: agregue una variable acumulador para que en cada vuelta del dataframe acceda a la columna de INVERSIONES e INVERSIONES en USD , tome el valor y luego lo sume.  Por ultimo antes de agregar el "consololidado_actual" al context, sume el total de inversiones en pesos y en dólares .

**Comment by joseent** [comment]
- [ ]  Columna de USD debe poder ver el detalle de datos(usar de guia columna de bancos)
- [ ] USD de banco, deben pesificarse para caja total de la misma manera que la columna de moneda extranjera
