### ISSUE TITLE
Baja y alta de cuentas corrientes

### ISSUE THREAD

**Issue by florm2496** [AbelMRobra/linkapp#59]
Requisito: poder realizar el alta y baja de cuentas corrientes de clientes. Se agrego la opción de baja en el botón de los tres puntitos que aparece para cada cliente en la lista de clientes de cada proyecto. Si el clientes esta activo, podrá ser dado de baja y viceversa.

**Comment by AbelMRobra** [comment]
Flujo de clientes -> Ver como afecta la baja de un cliente en el flujo
No eliminar del flujo a los clientes de baja
Botón para rastrear la ultima cuota pagada dentro de un plan
Estados de cuenta -> Buscador versión boleto
Flujo de proyecto -> Poder ver histórico/combinado 
Flujo de cliente -> Ver combinado
